import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import ClientProviders from "./ClientProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bodyFont = localFont({
  src: "../../public/fonts/OCRAStd.otf",
  variable: "--bodyFont",
});

const bodyFont2 = localFont({
  src: "../../public/fonts/HelveticaNeueThin.otf",
  variable: "--bodyFont2",
});

const bodyFont3 = localFont({
  src: "../../public/fonts/HelveticaNeueMedium.otf",
  variable: "--bodyFont3",
});

const headingFont = localFont({
  src: "../../public/fonts/BytePoliceSuperItalic.otf",
  variable: "--headingFont",
});

const headingFont2 = localFont({
  src: "../../public/fonts/DrukWide-Medium.otf",
  variable: "--headingFont2",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClientProviders>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${headingFont.variable} ${bodyFont.variable} ${headingFont2.variable} ${bodyFont2.variable} ${bodyFont3.variable}`}
        >
          {children}
        </body>
      </html>
    </ClientProviders>
  );
}
